version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/task_manager
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
